"""
This type stub file was generated by pyright.
"""

from sys import version_info as _swig_python_version_info

if _swig_python_version_info < (2, 7, 0):
    ...
if __package__ or "." in __name__:
    ...
else:
    ...
class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = ...


class VirtualMem:
    r"""Proxy of C++ CPLVirtualMemShadow class."""
    thisown = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    __repr__ = ...
    __swig_destroy__ = ...
    def GetAddr(self) -> void:
        r"""GetAddr(VirtualMem self)"""
        ...
    
    def Pin(self, start_offset: size_t = ..., nsize: size_t = ..., bWriteOp: int = ...) -> void:
        r"""Pin(VirtualMem self, size_t start_offset=0, size_t nsize=0, int bWriteOp=0)"""
        ...
    


def TermProgress_nocb(dfProgress: double, pszMessage: "char const *" = ..., pData: "void *" = ...) -> int:
    r"""TermProgress_nocb(double dfProgress, char const * pszMessage=None, void * pData=None) -> int"""
    ...

TermProgress = ...
def OpenNumPyArray(psArray: "PyArrayObject *", binterleave: bool) -> "GDALDatasetShadow *":
    r"""OpenNumPyArray(PyArrayObject * psArray, bool binterleave) -> Dataset"""
    ...

def OpenMultiDimensionalNumPyArray(psArray: "PyArrayObject *") -> "GDALDatasetShadow *":
    r"""OpenMultiDimensionalNumPyArray(PyArrayObject * psArray) -> Dataset"""
    ...

def GetArrayFilename(psArray: "PyArrayObject *") -> "retStringAndCPLFree *":
    r"""GetArrayFilename(PyArrayObject * psArray) -> retStringAndCPLFree *"""
    ...

def BandRasterIONumPy(band: Band, bWrite: int, xoff: double, yoff: double, xsize: double, ysize: double, psArray: PyArrayObject * <Parse Error>, buf_type: GDALDataType, resample_alg: GDALRIOResampleAlg, callback: GDALProgressFunc = ..., callback_data: void * <Parse Error> = ...) -> CPLErr:
    r"""BandRasterIONumPy(Band band, int bWrite, double xoff, double yoff, double xsize, double ysize, PyArrayObject * psArray, GDALDataType buf_type, GDALRIOResampleAlg resample_alg, GDALProgressFunc callback=0, void * callback_data=None) -> CPLErr"""
    ...

def DatasetIONumPy(ds: Dataset, bWrite: int, xoff: double, yoff: double, xsize: double, ysize: double, psArray: PyArrayObject * <Parse Error>, buf_type: GDALDataType, resample_alg: GDALRIOResampleAlg, callback: GDALProgressFunc = ..., callback_data: void * <Parse Error> = ..., binterleave: bool = ..., band_list: int = ...) -> CPLErr:
    r"""DatasetIONumPy(Dataset ds, int bWrite, double xoff, double yoff, double xsize, double ysize, PyArrayObject * psArray, GDALDataType buf_type, GDALRIOResampleAlg resample_alg, GDALProgressFunc callback=0, void * callback_data=None, bool binterleave=True, int band_list=0) -> CPLErr"""
    ...

def MDArrayIONumPy(bWrite: bool, mdarray: GDALMDArrayHS * <Parse Error>, psArray: PyArrayObject * <Parse Error>, nDims1: int, nDims3: int, buffer_datatype: GDALExtendedDataTypeHS * <Parse Error>) -> CPLErr:
    r"""MDArrayIONumPy(bool bWrite, GDALMDArrayHS * mdarray, PyArrayObject * psArray, int nDims1, int nDims3, GDALExtendedDataTypeHS * buffer_datatype) -> CPLErr"""
    ...

def VirtualMemGetArray(virtualmem: VirtualMem) -> int:
    r"""VirtualMemGetArray(VirtualMem virtualmem)"""
    ...

def RATValuesIONumPyWrite(poRAT: RasterAttributeTable, nField: int, nStart: int, psArray: PyArrayObject * <Parse Error>) -> CPLErr:
    r"""RATValuesIONumPyWrite(RasterAttributeTable poRAT, int nField, int nStart, PyArrayObject * psArray) -> CPLErr"""
    ...

def RATValuesIONumPyRead(poRAT: RasterAttributeTable, nField: int, nStart: int, nLength: int) -> PyObject * <Parse Error>:
    r"""RATValuesIONumPyRead(RasterAttributeTable poRAT, int nField, int nStart, int nLength) -> PyObject *"""
    ...

codes = ...
def OpenArray(array, prototype_ds=..., interleave=...): # -> None:
    ...

def flip_code(code): # -> None:
    ...

def NumericTypeCodeToGDALTypeCode(numeric_type): # -> None:
    ...

def GDALTypeCodeToNumericTypeCode(gdal_code): # -> None:
    ...

def LoadFile(filename, xoff=..., yoff=..., xsize=..., ysize=..., buf_xsize=..., buf_ysize=..., buf_type=..., resample_alg=..., callback=..., callback_data=..., interleave=..., band_list=...): # -> NDArray[floating[_32Bit] | signedinteger[_8Bit]] | None:
    ...

def SaveArray(src_array, filename, format=..., prototype=..., interleave=...):
    ...

def DatasetReadAsArray(ds, xoff=..., yoff=..., win_xsize=..., win_ysize=..., buf_obj=..., buf_xsize=..., buf_ysize=..., buf_type=..., resample_alg=..., callback=..., callback_data=..., interleave=..., band_list=...): # -> NDArray[floating[_32Bit] | signedinteger[_8Bit]] | None:
    """Pure python implementation of reading a chunk of a GDAL file
    into a numpy array.  Used by the gdal.Dataset.ReadAsArray method."""
    ...

def DatasetWriteArray(ds, array, xoff=..., yoff=..., band_list=..., interleave=..., resample_alg=..., callback=..., callback_data=...): # -> Literal[0]:
    """Pure python implementation of writing a chunk of a GDAL file
    from a numpy array.  Used by the gdal.Dataset.WriteArray method."""
    ...

def BandReadAsArray(band, xoff=..., yoff=..., win_xsize=..., win_ysize=..., buf_xsize=..., buf_ysize=..., buf_type=..., buf_obj=..., resample_alg=..., callback=..., callback_data=...): # -> NDArray[floating[_32Bit] | signedinteger[_8Bit]] | None:
    """Pure python implementation of reading a chunk of a GDAL file
    into a numpy array.  Used by the gdal.Band.ReadAsArray method."""
    ...

def BandWriteArray(band, array, xoff=..., yoff=..., resample_alg=..., callback=..., callback_data=...): # -> Literal[0]:
    """Pure python implementation of writing a chunk of a GDAL file
    from a numpy array.  Used by the gdal.Band.WriteArray method."""
    ...

def ExtendedDataTypeToNumPyDataType(dt): # -> type[bytes_] | float32 | dtype[void]:
    ...

def MDArrayReadAsArray(mdarray, array_start_idx=..., count=..., array_step=..., buffer_datatype=..., buf_obj=...): # -> NDArray[void | bytes_ | floating[_32Bit]]:
    ...

def MDArrayWriteArray(mdarray, array, array_start_idx=..., array_step=...): # -> Literal[0]:
    ...

def RATWriteArray(rat, array, field, start=...): # -> Literal[0]:
    """
    Pure Python implementation of writing a chunk of the RAT
    from a numpy array. Type of array is coerced to one of the types
    (int, double, string) supported. Called from RasterAttributeTable.WriteArray
    """
    ...

def RATReadArray(rat, field, start=..., length=...): # -> None:
    """
    Pure Python implementation of reading a chunk of the RAT
    into a numpy array. Called from RasterAttributeTable.ReadAsArray
    """
    ...

def CopyDatasetInfo(src, dst, xoff=..., yoff=...): # -> None:
    """
    Copy georeferencing information and metadata from one dataset to another.
    src: input dataset
    dst: output dataset - It can be a ROI -
    xoff, yoff:  dst's offset with respect to src in pixel/line.

    Notes: Destination dataset must have update access.  Certain formats
           do not support creation of geotransforms and/or gcps.

    """
    ...

