"""
This type stub file was generated by pyright.
"""

from sys import version_info as _swig_python_version_info
from . import ogr

if _swig_python_version_info < (2, 7, 0):
    ...
if __package__ or "." in __name__:
    ...
else:
    ...
class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = ...


def GetUseExceptions(*args) -> int:
    r"""GetUseExceptions() -> int"""
    ...

def UseExceptions(*args) -> void:
    r"""UseExceptions()"""
    ...

def DontUseExceptions(*args) -> void:
    r"""DontUseExceptions()"""
    ...

GATDijkstraShortestPath = ...
GATKShortestPath = ...
GATConnectedComponents = ...
GNM_EDGE_DIR_BOTH = ...
GNM_EDGE_DIR_SRCTOTGT = ...
GNM_EDGE_DIR_TGTTOSRC = ...
def CastToNetwork(*args) -> "GNMNetworkShadow *":
    r"""CastToNetwork(MajorObject base) -> Network"""
    ...

def CastToGenericNetwork(*args) -> "GNMGenericNetworkShadow *":
    r"""CastToGenericNetwork(MajorObject base) -> GenericNetwork"""
    ...

class Network(ogr.MajorObject):
    r"""Proxy of C++ GNMNetworkShadow class."""
    thisown = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    __repr__ = ...
    __swig_destroy__ = ...
    def ReleaseResultSet(self, *args) -> void:
        r"""ReleaseResultSet(Network self, Layer layer)"""
        ...
    
    def GetVersion(self, *args) -> int:
        r"""GetVersion(Network self) -> int"""
        ...
    
    def GetName(self, *args) -> "char const *":
        r"""GetName(Network self) -> char const *"""
        ...
    
    def GetFeatureByGlobalFID(self, *args) -> "OGRFeatureShadow *":
        r"""GetFeatureByGlobalFID(Network self, GIntBig GFID) -> Feature"""
        ...
    
    def GetPath(self, *args, **kwargs) -> "OGRLayerShadow *":
        r"""GetPath(Network self, GIntBig nStartFID, GIntBig nEndFID, GNMGraphAlgorithmType eAlgorithm, char ** options=None) -> Layer"""
        ...
    
    def DisconnectAll(self, *args) -> CPLErr:
        r"""DisconnectAll(Network self) -> CPLErr"""
        ...
    
    def GetProjection(self, *args) -> "char const *":
        r"""GetProjection(Network self) -> char const *"""
        ...
    
    def GetProjectionRef(self, *args) -> "char const *":
        r"""GetProjectionRef(Network self) -> char const *"""
        ...
    
    def GetFileList(self, *args) -> "char **":
        r"""GetFileList(Network self) -> char **"""
        ...
    
    def CreateLayer(self, *args, **kwargs) -> "OGRLayerShadow *":
        r"""CreateLayer(Network self, char const * name, SpatialReference srs=None, OGRwkbGeometryType geom_type=wkbUnknown, char ** options=None) -> Layer"""
        ...
    
    def CopyLayer(self, *args, **kwargs) -> "OGRLayerShadow *":
        r"""CopyLayer(Network self, Layer src_layer, char const * new_name, char ** options=None) -> Layer"""
        ...
    
    def DeleteLayer(self, *args) -> OGRErr:
        r"""DeleteLayer(Network self, int index) -> OGRErr"""
        ...
    
    def GetLayerCount(self, *args) -> int:
        r"""GetLayerCount(Network self) -> int"""
        ...
    
    def GetLayerByIndex(self, *args) -> "OGRLayerShadow *":
        r"""GetLayerByIndex(Network self, int index=0) -> Layer"""
        ...
    
    def GetLayerByName(self, *args) -> "OGRLayerShadow *":
        r"""GetLayerByName(Network self, char const * layer_name) -> Layer"""
        ...
    
    def TestCapability(self, *args) -> bool:
        r"""TestCapability(Network self, char const * cap) -> bool"""
        ...
    
    def StartTransaction(self, *args, **kwargs) -> OGRErr:
        r"""StartTransaction(Network self, int force=FALSE) -> OGRErr"""
        ...
    
    def CommitTransaction(self, *args) -> OGRErr:
        r"""CommitTransaction(Network self) -> OGRErr"""
        ...
    
    def RollbackTransaction(self, *args) -> OGRErr:
        r"""RollbackTransaction(Network self) -> OGRErr"""
        ...
    


class GenericNetwork(Network):
    r"""Proxy of C++ GNMGenericNetworkShadow class."""
    thisown = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    __repr__ = ...
    __swig_destroy__ = ...
    def ConnectFeatures(self, *args) -> CPLErr:
        r"""ConnectFeatures(GenericNetwork self, GIntBig nSrcFID, GIntBig nTgtFID, GIntBig nConFID, double dfCost, double dfInvCost, GNMDirection eDir) -> CPLErr"""
        ...
    
    def DisconnectFeatures(self, *args) -> CPLErr:
        r"""DisconnectFeatures(GenericNetwork self, GIntBig nSrcFID, GIntBig nTgtFID, GIntBig nConFID) -> CPLErr"""
        ...
    
    def DisconnectFeaturesWithId(self, *args) -> CPLErr:
        r"""DisconnectFeaturesWithId(GenericNetwork self, GIntBig nFID) -> CPLErr"""
        ...
    
    def ReconnectFeatures(self, *args) -> CPLErr:
        r"""ReconnectFeatures(GenericNetwork self, GIntBig nSrcFID, GIntBig nTgtFID, GIntBig nConFID, double dfCost, double dfInvCost, GNMDirection eDir) -> CPLErr"""
        ...
    
    def CreateRule(self, *args) -> CPLErr:
        r"""CreateRule(GenericNetwork self, char const * pszRuleStr) -> CPLErr"""
        ...
    
    def DeleteAllRules(self, *args) -> CPLErr:
        r"""DeleteAllRules(GenericNetwork self) -> CPLErr"""
        ...
    
    def DeleteRule(self, *args) -> CPLErr:
        r"""DeleteRule(GenericNetwork self, char const * pszRuleStr) -> CPLErr"""
        ...
    
    def GetRules(self, *args) -> "char **":
        r"""GetRules(GenericNetwork self) -> char **"""
        ...
    
    def ConnectPointsByLines(self, *args, **kwargs) -> CPLErr:
        r"""ConnectPointsByLines(GenericNetwork self, char ** papszLayerList, double dfTolerance, double dfCost, double dfInvCost, GNMDirection eDir) -> CPLErr"""
        ...
    
    def ChangeBlockState(self, *args) -> CPLErr:
        r"""ChangeBlockState(GenericNetwork self, GIntBig nFID, bool bIsBlock) -> CPLErr"""
        ...
    
    def ChangeAllBlockState(self, *args) -> CPLErr:
        r"""ChangeAllBlockState(GenericNetwork self, bool bIsBlock=False) -> CPLErr"""
        ...
    


