"""
This type stub file was generated by pyright.
"""

from ._compression.backend import *
from ._compression.format import *

""" The functions related to the LAZ format (compressed LAS)
"""
__all__ = ["LazBackend", "is_point_format_compressed", "compressed_id_to_uncompressed", "uncompressed_id_to_compressed", "DecompressionSelection"]
