"""
This type stub file was generated by pyright.
"""

import io
import os
import numpy as np
from dataclasses import dataclass
from queue import Queue, SimpleQueue
from threading import Thread
from typing import Iterator, List, Optional, Tuple, Union
from .compression import DecompressionSelection
from .point.record import ScaleAwarePointRecord
from .vlrs.known import BaseKnownVLR

DEFAULT_HTTP_WORKERS_NUM = ...
def requests_retry_session(retries=..., backoff_factor=..., status_forcelist=..., session=...): # -> Session:
    ...

class HttpRangeStream:
    """
    class used to mimic file-object interface for HTTP endpoints.

    This works by using Range-Requests.
    """
    def __init__(self, url: str) -> None:
        ...
    
    def seek(self, pos, whence=...): # -> None:
        ...
    
    def read(self, n) -> bytes:
        ...
    
    def tell(self) -> int:
        ...
    
    def close(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args, **kwargs): # -> None:
        ...
    


class CopcInfoVlr(BaseKnownVLR):
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['copc']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[1]]:
        ...
    
    def record_data_bytes(self):
        ...
    
    def parse_record_data(self, record_data_bytes: bytes): # -> None:
        ...
    


@dataclass
class Bounds:
    mins: np.ndarray
    maxs: np.ndarray
    def overlaps(self, other: Bounds) -> bool:
        ...
    
    def ensure_3d(self, mins: np.ndarray, maxs: np.ndarray) -> Bounds:
        ...
    


class VoxelKey:
    """
    Represents the `VoxelKey` struct of the COPC Specification
    """
    __slots__ = ...
    unpacker = ...
    def __init__(self) -> None:
        ...
    
    @classmethod
    def from_bytes(cls, data: bytes): # -> Self:
        ...
    
    def child(self, dir: int) -> VoxelKey:
        ...
    
    def childs(self) -> Iterator[VoxelKey]:
        ...
    
    def bounds(self, root_bounds: Bounds) -> Bounds:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __eq__(self, other: VoxelKey) -> bool:
        ...
    
    def __repr__(self) -> str:
        ...
    


class Entry:
    """
    Represents the `Entry` struct of the COPC Specification
    """
    __slots__ = ...
    unpacker = ...
    def __init__(self) -> None:
        ...
    
    @classmethod
    def from_bytes(cls, data: bytes) -> Entry:
        ...
    
    def __repr__(self) -> str:
        ...
    


class HierarchyPage:
    """
    Represents the `HierarchyPage` struct of the COPC Specification
    """
    def __init__(self) -> None:
        ...
    
    @classmethod
    def from_bytes(cls, data: bytes) -> HierarchyPage:
        ...
    


class CopcHierarchyVlr(BaseKnownVLR):
    """ "
    Hierarchy VLR from COPC Specification
    """
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['copc']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[1000]]:
        ...
    
    def record_data_bytes(self):
        ...
    
    def parse_record_data(self, record_data_bytes: bytes): # -> None:
        ...
    


class OctreeNode:
    """Our 'custom' type to build an octree from COPC hierarchy page"""
    def __init__(self) -> None:
        ...
    
    def remove_child(self, child: OctreeNode) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


def load_octree_for_query(source, info: CopcInfoVlr, hierarchy_page: HierarchyPage, query_bounds: Optional[Bounds] = ..., level_range: Optional[range] = ...) -> List[OctreeNode]:
    """
    Loads the nodes of the COPC octree from the `source` that
    satisfies the parameters `query_bounds` and `level_range`.

    It returns the root node of the loaded 'sub-octree'
    """
    ...

class ChunkIter:
    """
    Simple iterator that returns slices to chunks of byte.
    """
    def __init__(self, buffer: bytearray) -> None:
        ...
    
    def next(self, size: int): # -> memoryview[int]:
        ...
    


class HttpFetcherThread(Thread):
    def __init__(self, url: str, query_queue: Queue, result_queue: SimpleQueue) -> None:
        ...
    
    def run(self) -> None:
        ...
    


def http_queue_strategy(source: HttpRangeStream, byte_queries: List[Tuple[int, int]], out_compressed_bytes: bytearray, num_threads: int) -> None:
    ...

def http_thread_executor_strategy(source: HttpRangeStream, byte_queries: List[Tuple[int, int]], out_compressed_bytes: bytearray, num_threads: int) -> None:
    ...

class CopcReader:
    """
    Class allowing to do queries over a `COPC`_ LAZ

    In short, COPC files are LAZ 1.4 files organized in a particular way
    (Octree) making it possible to do spatial queries
    as well as queries with a level of details.

    CopcReader **requires** the ``lazrs`` backend to work.

    Optionaly, if ``requests`` is installed, CopcReader can handle
    Copc files that are on a remote HTTP server

    This class *only* reads COPC files, it does not support normal
    LAS/LAZ files.

    To create an instance of it you'll likely
    want to use the :meth:`.CopcReader.open` constructor


    .. versionadded:: 2.2

    .. _COPC: https://github.com/copcio/copcio.github.io
    """
    def __init__(self, stream, close_fd: bool = ..., http_num_threads: int = ..., _http_strategy: str = ..., decompression_selection: DecompressionSelection = ...) -> None:
        """
        Creates a CopcReader.

        Parameters
        ---------

        stream: the stream from where data can be read.
                It must have the following file object methods:
                read, seek, tell

        http_num_threads: int, optional, default num cpu * 5
            Number of worker threads to do concurent HTTP requests,
            ignored when reading non-HTTP file

        close_fd: optional, default bool
            Whether the stream/file object shall be closed, this only work
            when using the CopcReader in a with statement.

        decompression_selection: DecompressionSelection,
            see :func:`laspy.open`



        .. versionadded:: 2.4
            The ``decompression_selection`` parameter.
        """
        ...
    
    @classmethod
    def open(cls, source: Union[str, os.PathLike, io.IOBase], http_num_threads: int = ..., _http_strategy: str = ..., decompression_selection: DecompressionSelection = ...) -> CopcReader:
        """
        Opens the COPC file.


        Parameters
        ----------
        source: str, io.IOBase, uri or file-like object of the COPC file.
            Supported sources are:

                - 'local' files accesible with a path.
                - HTTP / HTTPS endpoints. The pyhon package ``requests`` is
                  required in order to be able to work with HTTP endpoints.
                - file-like objects, e.g. fsspec io.IOBase objects.

        http_num_threads: int, optional, default num cpu * 5
            Number of worker threads to do concurent HTTP requests,
            ignored when reading non-HTTP file

        decompression_selection: DecompressionSelection,
            see :func:`laspy.open`


        Opening a local file

        .. code-block:: Python

            from laspy import CopcReader

            with CopcReader.open("some_file.laz") as reader:
                ...

        Opening a file on a remite HTTP server
        (``requests`` package required)

        .. code-block:: Python

            from laspy import CopcReader

            url = "https://s3.amazonaws.com/hobu-lidar/autzen-classified.copc.laz"
            with CopcReader.open(url) as reader:
                ...



        .. versionadded:: 2.4
            The ``decompression_selection`` parameter.
        """
        ...
    
    def query(self, bounds: Optional[Bounds] = ..., resolution: Optional[Union[float, int]] = ..., level: Optional[Union[int, range]] = ...) -> ScaleAwarePointRecord:
        """ "
        Query the COPC file to retrieve the points matching the
        requested bounds and level.

        Parameters
        ----------
        bounds: Bounds, optional, default None
                The bounds for which you wish to aquire points.
                If None, the whole file's bounds will be considered
                2D bounds are suported, (No point will be filtered on its Z coordinate)

        resolution: float or int, optional, default None
                Limits the octree levels to be queried in order to have
                a point cloud with the requested resolution.

                - The unit is the one of the data.

                - If None, the resulting cloud will be at the
                  full resolution offered by the COPC source

                - Mutually exclusive with level parameter

        level: int or range, optional, default None
               The level of detail (LOD).

               - If None, all LOD are going to be considered
               - If it is an int, only points that are of the requested LOD
                 will be returned.
               - If it is a range, points for which the LOD is within the range
                 will be returned
        """
        ...
    
    def spatial_query(self, bounds: Bounds) -> ScaleAwarePointRecord:
        ...
    
    def level_query(self, level: Union[int, range]) -> ScaleAwarePointRecord:
        ...
    
    def __enter__(self) -> CopcReader:
        ...
    
    def __exit__(self, _exc_type, _exc_val, _exc_tb) -> None:
        ...
    


