"""
This type stub file was generated by pyright.
"""

""" All the custom exceptions types
"""
class LaspyException(Exception):
    ...


class UnknownExtraType(LaspyException):
    ...


class PointFormatNotSupported(LaspyException):
    ...


class FileVersionNotSupported(LaspyException):
    ...


class LazError(LaspyException):
    ...


class IncompatibleDataFormat(LaspyException):
    ...


