"""
This type stub file was generated by pyright.
"""

import enum
import typing
from typing import BinaryIO, Iterable, List, NamedTuple, Optional, Union
from .point.format import ExtraBytesParams, PointFormat
from .point.record import PackedPointRecord
from .vlrs import VLR
from .vlrs.vlrlist import VLRList

logger = ...
GENERATING_SOFTWARE_LEN = ...
SYSTEM_IDENTIFIER_LEN = ...
LAS_FILE_SIGNATURE = ...
DEFAULT_GENERATING_SOFTWARE = ...
class Version(NamedTuple):
    major: int
    minor: int
    @classmethod
    def from_str(cls, string: str) -> Version:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    


class GpsTimeType(enum.IntEnum):
    WEEK_TIME = ...
    STANDARD = ...


class GlobalEncoding:
    GPS_TIME_TYPE_MASK = ...
    WAVEFORM_INTERNAL_MASK = ...
    WAVEFORM_EXTERNAL_MASK = ...
    SYNTHETIC_RETURN_NUMBERS_MASK = ...
    WKT_MASK = ...
    def __init__(self, value=...) -> None:
        ...
    
    @property
    def gps_time_type(self) -> GpsTimeType:
        ...
    
    @gps_time_type.setter
    def gps_time_type(self, value: GpsTimeType): # -> None:
        ...
    
    @property
    def waveform_data_packets_internal(self) -> bool:
        ...
    
    @waveform_data_packets_internal.setter
    def waveform_data_packets_internal(self, value): # -> None:
        ...
    
    @property
    def waveform_data_packets_external(self) -> bool:
        ...
    
    @waveform_data_packets_external.setter
    def waveform_data_packets_external(self, value): # -> None:
        ...
    
    @property
    def synthetic_return_numbers(self) -> bool:
        ...
    
    @synthetic_return_numbers.setter
    def synthetic_return_numbers(self, value): # -> None:
        ...
    
    @property
    def wkt(self) -> bool:
        ...
    
    @wkt.setter
    def wkt(self, value): # -> None:
        ...
    
    @classmethod
    def read_from(cls, stream: BinaryIO) -> GlobalEncoding:
        ...
    
    def write_to(self, stream: BinaryIO) -> None:
        ...
    


class LasHeader:
    """Contains the information from the header of as LAS file
    with 'implementation' field left out and 'users' field
    stored in more ergonomic classes.

    This header also contains the VLRs

    Examples
    --------

    Creating a default header:

    >>> header = LasHeader()
    >>> header
    <LasHeader(1.2, <PointFormat(3, 0 bytes of extra dims)>)>

    Creating a header with the wanted version and point format:

    >>> header = LasHeader(version=Version(1, 4), point_format=PointFormat(6))
    >>> header
    <LasHeader(1.4, <PointFormat(6, 0 bytes of extra dims)>)>

    >>> header = LasHeader(version="1.4", point_format=6)
    >>> header
    <LasHeader(1.4, <PointFormat(6, 0 bytes of extra dims)>)>
    """
    DEFAULT_VERSION = ...
    DEFAULT_POINT_FORMAT = ...
    _OLD_LASPY_NAMES = ...
    def __init__(self, *, version: Optional[Union[Version, str]] = ..., point_format: Optional[Union[PointFormat, int]] = ...) -> None:
        ...
    
    @property
    def point_format(self) -> PointFormat:
        """The point format"""
        ...
    
    @point_format.setter
    def point_format(self, new_point_format: PointFormat) -> None:
        ...
    
    @property
    def version(self) -> Version:
        """The version"""
        ...
    
    @version.setter
    def version(self, version: Version) -> None:
        ...
    
    @property
    def x_scale(self) -> float:
        ...
    
    @x_scale.setter
    def x_scale(self, value: float) -> None:
        ...
    
    @property
    def y_scale(self) -> float:
        ...
    
    @y_scale.setter
    def y_scale(self, value: float) -> None:
        ...
    
    @property
    def z_scale(self) -> float:
        ...
    
    @z_scale.setter
    def z_scale(self, value: float) -> None:
        ...
    
    @property
    def x_offset(self) -> float:
        ...
    
    @x_offset.setter
    def x_offset(self, value: float) -> None:
        ...
    
    @property
    def y_offset(self) -> float:
        ...
    
    @y_offset.setter
    def y_offset(self, value: float) -> None:
        ...
    
    @property
    def z_offset(self) -> float:
        ...
    
    @z_offset.setter
    def z_offset(self, value: float) -> None:
        ...
    
    @property
    def x_max(self) -> float:
        ...
    
    @x_max.setter
    def x_max(self, value: float) -> None:
        ...
    
    @property
    def y_max(self) -> float:
        ...
    
    @y_max.setter
    def y_max(self, value: float) -> None:
        ...
    
    @property
    def z_max(self) -> float:
        ...
    
    @z_max.setter
    def z_max(self, value: float) -> None:
        ...
    
    @property
    def x_min(self) -> float:
        ...
    
    @x_min.setter
    def x_min(self, value: float) -> None:
        ...
    
    @property
    def y_min(self) -> float:
        ...
    
    @y_min.setter
    def y_min(self, value: float) -> None:
        ...
    
    @property
    def z_min(self) -> float:
        ...
    
    @z_min.setter
    def z_min(self, value: float) -> None:
        ...
    
    @property
    def vlrs(self) -> VLRList:
        ...
    
    @vlrs.setter
    def vlrs(self, vlrs: typing.Iterable[VLR]) -> None:
        ...
    
    def add_extra_dims(self, params: List[ExtraBytesParams]) -> None:
        ...
    
    def add_extra_dim(self, params: ExtraBytesParams): # -> None:
        ...
    
    def add_crs(self, crs: pyproj.CRS, keep_compatibility: bool = ...) -> None:
        """Add a Coordinate Reference System VLR from a pyproj CRS object.

        The type of VLR created depends on the las version and point format
        version. Las version >= 1.4 use WKT string, las version < 1.4 and point
        format < 6 use GeoTiff tags.

        .. warning::
            This requires `pyproj`.

        .. warning::
            Not all CRS are supported when adding GeoTiff tags.
            For example, custom CRS.

            Typically, if the CRS has an EPSG code it will be supported.
        """
        ...
    
    def remove_extra_dim(self, name: str) -> None:
        ...
    
    def remove_extra_dims(self, names: Iterable[str]) -> None:
        ...
    
    def set_version_and_point_format(self, version: Version, point_format: PointFormat) -> None:
        ...
    
    def partial_reset(self) -> None:
        ...
    
    def update(self, points: PackedPointRecord) -> None:
        ...
    
    def grow(self, points: PackedPointRecord) -> None:
        ...
    
    def set_compressed(self, state: bool) -> None:
        ...
    
    def max_point_count(self) -> int:
        ...
    
    def copy(self): # -> Self:
        ...
    
    @classmethod
    def read_from(cls, original_stream: BinaryIO, read_evlrs: bool = ...) -> LasHeader:
        """
        Reads the header from the stream

        read_evlrs: If true, evlrs will be read

        Leaves the stream pos right before the point starts
        (regardless of is read_evlrs was true)

        """
        ...
    
    def write_to(self, stream: BinaryIO, ensure_same_size: bool = ..., encoding_errors: str = ...) -> None:
        """
        ensure_same_size: if true this function will raise an internal error
        if the written header would change the offset to point data
        it originally had (meaning the file could become broken),
        Used when rewriting a header to update the file (new point count, mins, maxs, etc)
        """
        ...
    
    def parse_crs(self, prefer_wkt=...) -> Optional[pyproj.CRS]:
        """
        Method to parse OGC WKT or GeoTiff VLR keys into a pyproj CRS object

        Returns None if no CRS VLR is present, or if the CRS specified
        in the VLRS is not understood.


        Parameters
        ----------
        prefer_wkt: Optional, default True,
            If True the WKT VLR will be preferred in case
            both the WKT and Geotiff VLR are present

        .. warning::
            This requires `pyproj`.

        .. versionadded:: 2.5
            The ``prefer_wkt`` parameters.
        """
        ...
    
    def read_evlrs(self, stream): # -> None:
        """
        Reads EVLRs from the stream and sets them in the
        data property.

        The evlrs are accessed from the `evlrs` property

        Does nothing if either of these is true:
            - The file does not support EVLRS (version < 1.4)
            - The file has no EVLRS
            - The stream does not support seeking

        Leaves/restores the stream position to where it was before the call
        """
        ...
    
    @property
    def major_version(self) -> int:
        ...
    
    @property
    def minor_version(self) -> int:
        ...
    
    def __getattr__(self, item): # -> Any:
        ...
    
    def __setattr__(self, key, value): # -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


LAS_HEADERS_SIZE = ...
