"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO, Iterable, Optional, Union
from ._pointappender import IPointAppender
from .compression import LazBackend
from .point.record import PackedPointRecord

class LasAppender:
    """Allows to append points to and existing LAS/LAZ file.

    Appending to LAZ is only supported by the lazrs backend
    """
    def __init__(self, dest: BinaryIO, laz_backend: Optional[Union[LazBackend, Iterable[LazBackend]]] = ..., closefd: bool = ..., encoding_errors: str = ...) -> None:
        ...
    
    def append_points(self, points: PackedPointRecord) -> None:
        """Append the points to the file, the points
        must have the same point format as the points
        already contained within the file.

        :param points: The points to append
        """
        ...
    
    def close(self) -> None:
        ...
    
    def __enter__(self) -> LasAppender:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
    


class UncompressedPointAppender(IPointAppender):
    """
    Appending points in the simple uncompressed case.
    """
    def __init__(self, dest: BinaryIO) -> None:
        ...
    
    def append_points(self, points: PackedPointRecord) -> None:
        ...
    
    def done(self) -> None:
        ...
    


