"""
This type stub file was generated by pyright.
"""

import typing
import numpy as np
from typing import BinaryIO, Iterable, List, Optional, Sequence, Union, overload
from .compression import LazBackend
from .header import LasHeader
from .point import ExtraBytesParams, PointFormat, record
from .point.dims import ScaledArrayView, SubFieldView
from .vlrs.vlrlist import VLRList

logger = ...
class LasData:
    """Class synchronizing all the moving parts of LAS files.

    It connects the point record, header, vlrs together.

    To access points dimensions using this class you have two possibilities

    .. code:: python

        las = laspy.read('some_file.las')
        las.classification
        # or
        las['classification']
    """
    def __init__(self, header: LasHeader, points: Optional[Union[record.PackedPointRecord, record.ScaleAwarePointRecord]] = ...) -> None:
        ...
    
    @property
    def point_format(self) -> PointFormat:
        """Shortcut to get the point format"""
        ...
    
    @property
    def xyz(self) -> np.ndarray:
        """Returns a **new** 2D numpy array with the x,y,z coordinates

        >>> import laspy
        >>> las = laspy.read("tests/data/simple.las")
        >>> xyz = las.xyz
        >>> xyz.ndim
        2
        >>> xyz.shape
        (1065, 3)
        >>> bool(np.all(xyz[..., 0] == las.x))
        True
        """
        ...
    
    @xyz.setter
    def xyz(self, value) -> None:
        ...
    
    @property
    def points(self) -> record.PackedPointRecord:
        """Returns the point record"""
        ...
    
    @points.setter
    def points(self, new_points: record.PackedPointRecord) -> None:
        ...
    
    @property
    def vlrs(self) -> VLRList:
        ...
    
    @vlrs.setter
    def vlrs(self, vlrs) -> None:
        ...
    
    @property
    def evlrs(self) -> Optional[VLRList]:
        ...
    
    @evlrs.setter
    def evlrs(self, evlrs: VLRList) -> None:
        ...
    
    def add_extra_dim(self, params: ExtraBytesParams) -> None:
        """Adds a new extra dimension to the point record

        .. note::

            If you plan on adding multiple extra dimensions,
            prefer :meth:`.add_extra_dims` as it will
            save re-allocations and data copy

        Parameters
        ----------
        params : ExtraBytesParams
            parameters of the new extra dimension to add

        """
        ...
    
    def add_extra_dims(self, params: List[ExtraBytesParams]) -> None:
        """Add multiple extra dimensions at once

        Parameters
        ----------

        params: list of parameters of the new extra dimensions to add
        """
        ...
    
    def remove_extra_dims(self, names: Iterable[str]) -> None:
        """Remove multiple extra dimensions from this object

        Parameters
        ----------

        names: iterable,
            names of the extra dimensions to be removed


        Raises
        ------

        LaspyException: if you try to remove an extra dimension that do not exist.

        """
        ...
    
    def remove_extra_dim(self, name: str) -> None:
        """Remove an extra dimensions from this object

        .. note::

             If you plan on removing multiple extra dimensions,
             prefer :meth:`.remove_extra_dims` as it will
             save re-allocations and data copy

        Parameters
        ----------

        name: str,
            name of the extra dimension to be removed


        Raises
        ------

        LaspyException: if you try to remove an extra dimension that do not exist.

        """
        ...
    
    def update_header(self) -> None:
        """Update the information stored in the header
        to be in sync with the actual data.

        This method is called automatically when you save a file using
        :meth:`laspy.lasdatas.base.LasBase.write`
        """
        ...
    
    @overload
    def write(self, destination: str, laz_backend: Optional[Union[LazBackend, Sequence[LazBackend]]] = ...) -> None:
        ...
    
    @overload
    def write(self, destination: BinaryIO, do_compress: Optional[bool] = ..., laz_backend: Optional[Union[LazBackend, Sequence[LazBackend]]] = ...) -> None:
        ...
    
    def write(self, destination, do_compress=..., laz_backend=...): # -> None:
        """Writes to a stream or file

        .. note::

            When destination is a string, it will be interpreted as the path were the file should be written to,
            and whether the file will be compressed depends on the extension used (case insensitive):

                - .laz -> compressed
                - .las -> uncompressed

            And the do_compress option will be ignored


        Parameters
        ----------
        destination: str or file object
            filename or stream to write to
        do_compress: bool, optional
            Flags to indicate if you want to compress the data
        laz_backend: optional, the laz backend to use
            By default, laspy detect available backends
        """
        ...
    
    def change_scaling(self, scales=..., offsets=...) -> None:
        """This changes the scales and/or offset used for the x,y,z
        dimensions.

        It recomputes the internal, non-scaled X,Y,Z dimensions
        to match the new scales and offsets.

        It also updates the header with the new values of scales and offsets.

        Parameters
        ----------
        scales: optional
                New scales to be used. If not provided, the scales won't change.
        offsets: optional
                 New offsets to be used. If not provided, the offsets won't change.

        Example
        -------

        >>> import laspy
        >>> header = laspy.LasHeader()
        >>> header.scales = np.array([0.1, 0.1, 0.1])
        >>> header.offsets = np.array([0, 0 ,0])

        >>> las = laspy.LasData(header=header)
        >>> las.x = [10.0]
        >>> las.y = [20.0]
        >>> las.z = [30.0]

        >>> # X = (x - x_offset) / x_scale
        >>> assert np.all(las.xyz == [[10.0, 20., 30]])
        >>> assert np.all(las.X == [100])
        >>> assert np.all(las.Y == [200])
        >>> assert np.all(las.Z == [300])

        We change the scales (only changing x_scale here)
        but not the offsets.

        The xyz coordinates (double) are the same (minus possible rounding with actual coordinates)
        However the integer coordinates changed

        >>> las.change_scaling(scales=[0.01, 0.1, 0.1])
        >>> assert np.all(las.xyz == [[10.0, 20., 30]])
        >>> assert np.all(las.X == [1000])
        >>> assert np.all(las.Y == [200])
        >>> assert np.all(las.Z == [300])

        Same idea if we change the offsets, the xyz do not change
        but XYZ does

        >>> las.change_scaling(offsets=[0, 10, 15])
        >>> assert np.all(las.xyz == [[10.0, 20., 30]])
        >>> assert np.all(las.X == [1000])
        >>> assert np.all(las.Y == [100])
        >>> assert np.all(las.Z == [150])
        """
        ...
    
    def __getattr__(self, item): # -> ScaleAwarePointRecord | ScaledArrayView | PackedPointRecord | SubFieldView | NDArray[Any]:
        """Automatically called by Python when the attribute
        named 'item' is no found. We use this function to forward the call the
        point record. This is the mechanism used to allow the users to access
        the points dimensions directly through a LasData.

        Parameters
        ----------
        item: str
            name of the attribute, should be a dimension name

        Returns
        -------
        The requested dimension if it exists

        """
        ...
    
    def __setattr__(self, key, value): # -> None:
        """This is called on every access to an attribute of the instance.
        Again we use this to forward the call the the points record

        But this time checking if the key is actually a dimension name
        so that an error is raised if the user tries to set a valid
        LAS dimension even if it is not present in the field.
        eg: user tries to set the red field of a file with point format 0:
        an error is raised
        """
        ...
    
    @typing.overload
    def __getitem__(self, item: Union[str, List[str]]) -> Union[np.ndarray, ScaledArrayView, SubFieldView]:
        ...
    
    @typing.overload
    def __getitem__(self, item: Union[int, typing.Iterable[int], slice]) -> LasData:
        ...
    
    def __getitem__(self, item): # -> ScaleAwarePointRecord | ScaledArrayView | PackedPointRecord | SubFieldView | NDArray[Any] | LasData:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self) -> str:
        ...
    


