"""
This type stub file was generated by pyright.
"""

from . import lasdata
from .typehints import PathLike

WHOLE_FILE = ...
class LasMMAP(lasdata.LasData):
    """Memory map a LAS file.
    It works like a regular LasData however the data is not actually read in memory,

    Access to dimensions are made directly from the file itself, changes made to the points
    are directly reflected in the mmap file.

    Vlrs cannot be modified.

    This can be useful if you want to be able to process a big LAS file

    .. note::
        A LAZ (compressed LAS) cannot be mmapped
    """
    def __init__(self, filename: PathLike) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def __enter__(self) -> LasMMAP:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
    


