"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO, Iterable, Optional, Union
from ._compression.backend import LazBackend
from ._pointreader import IPointReader
from .compression import DecompressionSelection
from .header import LasHeader
from .lasdata import LasData
from .point import record
from .vlrs.vlrlist import VLRList

logger = ...
class LasReader:
    """The reader class handles LAS and LAZ via one of the supported backend"""
    def __init__(self, source: BinaryIO, closefd: bool = ..., laz_backend: Optional[Union[LazBackend, Iterable[LazBackend]]] = ..., read_evlrs: bool = ..., decompression_selection: DecompressionSelection = ...) -> None:
        """
        Initialize the LasReader

        Parameters
        ----------
        source: file_object
        closefd: bool, default True
        laz_backend: LazBackend or list of LazBackend, optional
        read_evlrs: bool, default True
            only applies to __init__ phase, and for files
            that support evlrs
        decompression_selection: optional, DecompressionSelection
            Selection of fields to decompress, only works form point format >= 6 <= 10
            Ignored on other point formats

        .. versionadded:: 2.4
            The ``read_evlrs`` and ``decompression_selection`` parameters.
        """
        ...
    
    @property
    def evlrs(self) -> Optional[VLRList]:
        ...
    
    @evlrs.setter
    def evlrs(self, evlrs: VLRList) -> None:
        ...
    
    @property
    def point_source(self) -> IPointReader:
        ...
    
    def read_points(self, n: int) -> record.ScaleAwarePointRecord:
        """Read n points from the file


        Will only read as many points as the header advertise.
        That is, if you ask to read 50 points and there are only 45 points left
        this function will only read 45 points.

        If there are no points left to read, returns an empty point record.

        Parameters
        ----------
        n: The number of points to read
           if n is less than 0, this function will read the remaining points
        """
        ...
    
    def read(self) -> LasData:
        """
        Reads all the points that are not read and returns a LasData object

        This will also read EVLRS

        """
        ...
    
    def seek(self, pos: int, whence: int = ...) -> int:
        """Seeks to the start of the point at the given pos

        Parameters
        ----------
        pos: index of the point to seek to
        whence: optional, controls how the pos parameter is interpreted:
                io.SEEK_SET: (default) pos is the index of the point from the beginning
                io.SEEK_CUR: pos is the point_index relative to the point_index of the last point read
                io.SEEK_END: pos is the point_index relative to last point
        Returns
        -------
        The index of the point the reader seeked to, relative to the first point
        """
        ...
    
    def chunk_iterator(self, points_per_iteration: int) -> PointChunkIterator:
        """Returns an iterator, that will read points by chunks
        of the requested size

        :param points_per_iteration: number of points to be read with each iteration
        :return:
        """
        ...
    
    def read_evlrs(self): # -> None:
        ...
    
    def close(self) -> None:
        """closes the file object used by the reader"""
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


class PointChunkIterator:
    def __init__(self, reader: LasReader, points_per_iteration: int) -> None:
        ...
    
    def __next__(self) -> record.ScaleAwarePointRecord:
        ...
    
    def __iter__(self) -> PointChunkIterator:
        ...
    


class UncompressedPointReader(IPointReader):
    """Implementation of IPointReader for the simple uncompressed case"""
    def __init__(self, source, header: LasHeader) -> None:
        ...
    
    @property
    def source(self):
        ...
    
    def read_n_points(self, n: int) -> bytearray:
        ...
    
    def seek(self, point_index: int) -> None:
        ...
    
    def close(self): # -> None:
        ...
    


class EmptyPointReader(IPointReader):
    """Does nothing but returning empty bytes.
    Used to make sure we handle empty LAS files in a robust way.
    """
    @property
    def source(self): # -> None:
        ...
    
    def read_n_points(self, n: int) -> bytearray:
        ...
    
    def close(self) -> None:
        ...
    
    def seek(self, point_index: int) -> None:
        ...
    


