"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO, Iterable, Optional, Union
from ._pointwriter import IPointWriter
from .compression import LazBackend
from .header import LasHeader
from .point.record import PackedPointRecord
from .vlrs.vlrlist import VLRList

logger = ...
class LasWriter:
    """
    Allows to write a complete LAS/LAZ file to the destination.
    """
    def __init__(self, dest: BinaryIO, header: LasHeader, do_compress: Optional[bool] = ..., laz_backend: Optional[Union[LazBackend, Iterable[LazBackend]]] = ..., closefd: bool = ..., encoding_errors: str = ...) -> None:
        """
        Parameters
        ----------
        dest: file_object
            file object where the LAS/LAZ will be written

        header: LasHeader
            The header of the file to be written

        do_compress: bool, optional
            Whether the file data should be written as LAS (uncompressed)
            or LAZ (compressed).
            If None, the file won't be compressed, unless a laz_backend is provided

        laz_backend: LazBackend or list of LazBackend, optional
            The LazBackend to use (or if it is a sequence the LazBackend to try)
            for the compression

        closefd: bool, default True
            should the `dest` be closed when the writer is closed

        encoding_errors: str, default 'strict'
            How encoding errors should be treated.
            Possible values and their explanation can be seen here:
            https://docs.python.org/3/library/codecs.html#error-handlers.
        """
        ...
    
    def write_points(self, points: PackedPointRecord) -> None:
        """
        .. note ::


            If the points type is PackedPointRecord, then you need to make sure
            the points are expressed in the same scales and offsets 'system' than
            this writer.

            You can use :meth:`.LasData.change_scaling` before getting the points
            to ensure that.

            If the points type is ScaleAwarePointsRecord, then points will automatically
            re-scaled.

        Parameters
        ----------
        points: PackedPointRecord or ScaleAwarePointRecord
                The points to be written

        Raises
        ------
        LaspyException
            If the point format of the points does not match
            the point format of the writer.
        """
        ...
    
    def write_evlrs(self, evlrs: VLRList) -> None:
        """Writes the EVLRs to the file

        Parameters
        ----------
        evlrs: VLRList
               The EVLRs to be written

        Raises
        ------
        LaspyException
            If the file's version is not >= 1.4
        """
        ...
    
    def close(self) -> None:
        """Closes the writer.

        flushes the points, updates the header, making it impossible
        to write points afterwards.
        """
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


class UncompressedPointWriter(IPointWriter):
    """
    Writing points in the simple uncompressed case.
    """
    def __init__(self, dest: BinaryIO) -> None:
        ...
    
    @property
    def destination(self) -> BinaryIO:
        ...
    
    def write_points(self, points: PackedPointRecord) -> None:
        ...
    
    def done(self) -> None:
        ...
    


