"""
This type stub file was generated by pyright.
"""

import enum
from abc import ABCMeta
from typing import Any, BinaryIO, Optional, Tuple
from .._pointappender import IPointAppender
from .._pointreader import IPointReader
from .._pointwriter import IPointWriter
from .lazbackend import ILazBackend
from .selection import DecompressionSelection

_DEFAULT_BACKENDS: Tuple[ILazBackend, ...] = ...
class ABCEnumMeta(enum.EnumMeta, ABCMeta):
    ...


class LazBackend(ILazBackend, enum.Enum, metaclass=ABCEnumMeta):
    """Supported backends for reading and writing LAS/LAZ"""
    LazrsParallel = ...
    Lazrs = ...
    Laszip = ...
    def is_available(self) -> bool:
        """Returns true if the backend is available"""
        ...
    
    @property
    def supports_append(self) -> bool:
        ...
    
    def create_appender(self, dest: BinaryIO, header: LasHeader) -> IPointAppender:
        ...
    
    def create_reader(self, source: Any, header: LasHeader, decompression_selection: Optional[DecompressionSelection] = ...) -> IPointReader:
        ...
    
    def create_writer(self, dest: Any, header: LasHeader) -> IPointWriter:
        ...
    
    @classmethod
    def detect_available(cls) -> Tuple[LazBackend, ...]:
        """Returns a tuple containing the available backends in the current
        python environment
        """
        ...
    


