"""
This type stub file was generated by pyright.
"""

def is_point_format_compressed(point_format_id: int) -> bool:
    ...

def compressed_id_to_uncompressed(point_format_id: int) -> int:
    ...

def uncompressed_id_to_compressed(point_format_id: int) -> int:
    ...

