"""
This type stub file was generated by pyright.
"""

from typing import Any, BinaryIO, Optional
from .._pointappender import IPointAppender
from .._pointreader import IPointReader
from .._pointwriter import IPointWriter
from ..header import LasHeader
from ..point.record import PackedPointRecord
from .lazbackend import ILazBackend
from .selection import DecompressionSelection

class LaszipBackend(ILazBackend):
    def is_available(self) -> bool:
        ...
    
    @property
    def supports_append(self) -> bool:
        ...
    
    def create_appender(self, dest: BinaryIO, header: LasHeader) -> IPointAppender:
        ...
    
    def create_reader(self, source: Any, header: LasHeader, decompression_selection: Optional[DecompressionSelection] = ...) -> IPointReader:
        ...
    
    def create_writer(self, dest: Any, header: LasHeader) -> IPointWriter:
        ...
    


class LaszipPointReader(IPointReader):
    """Implementation for the laszip backend"""
    def __init__(self, source: BinaryIO, header: LasHeader, decompression_selection: DecompressionSelection) -> None:
        ...
    
    @property
    def source(self): # -> BinaryIO:
        ...
    
    def read_n_points(self, n: int) -> bytearray:
        ...
    
    def seek(self, point_index: int) -> None:
        ...
    
    def close(self) -> None:
        ...
    


class LaszipPointWriter(IPointWriter):
    """
    Compressed point writer using laszip backend
    """
    def __init__(self, dest: BinaryIO, header: LasHeader) -> None:
        ...
    
    @property
    def destination(self) -> BinaryIO:
        ...
    
    def write_points(self, points: PackedPointRecord) -> None:
        ...
    
    def done(self) -> None:
        ...
    
    def write_initial_header_and_vlrs(self, header: LasHeader, encoding_errors: str) -> None:
        ...
    
    def write_updated_header(self, header: LasHeader, encoding_errors: str) -> None:
        ...
    


