"""
This type stub file was generated by pyright.
"""

from typing import Any, BinaryIO, List, Optional, Tuple
from .._pointappender import IPointAppender
from .._pointreader import IPointReader
from .._pointwriter import IPointWriter
from ..header import LasHeader
from ..point.format import PointFormat
from ..point.record import PackedPointRecord
from ..vlrs.known import LasZipVlr
from .lazbackend import ILazBackend
from .selection import DecompressionSelection

class LazrsBackend(ILazBackend):
    def __init__(self, parallel: bool = ...) -> None:
        ...
    
    def is_available(self) -> bool:
        ...
    
    @property
    def supports_append(self) -> bool:
        ...
    
    def create_appender(self, dest: BinaryIO, header: LasHeader) -> IPointAppender:
        ...
    
    def create_reader(self, source: Any, header: LasHeader, decompression_selection: Optional[DecompressionSelection] = ...) -> IPointReader:
        ...
    
    def create_writer(self, dest: Any, header: LasHeader) -> IPointWriter:
        ...
    


class LazrsPointReader(IPointReader):
    """Implementation for the laz-rs backend, supports single-threaded decompression
    as well as multi-threaded decompression
    """
    def __init__(self, source, laszip_vlr: LasZipVlr, parallel: bool, decompression_selection: DecompressionSelection) -> None:
        ...
    
    @property
    def source(self):
        ...
    
    def read_n_points(self, n: int) -> bytearray:
        ...
    
    def seek(self, point_index: int) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def read_chunk_table_only(self) -> List[Tuple[int, int]]:
        """
        This function requires the source to be at the start of the chunk table
        """
        ...
    
    def read_raw_bytes(self, n: int) -> bytes:
        """
        reads and returns exactly `n` bytes from the source used by
        this point reader.
        """
        ...
    


class LazrsPointWriter(IPointWriter):
    """
    Compressed point writer using lazrs backend
    """
    def __init__(self, dest: BinaryIO, point_format: PointFormat, parallel: bool) -> None:
        ...
    
    def write_initial_header_and_vlrs(self, header: LasHeader, encoding_errors: str) -> None:
        ...
    
    @property
    def destination(self) -> BinaryIO:
        ...
    
    def write_points(self, points: PackedPointRecord) -> None:
        ...
    
    def done(self) -> None:
        ...
    


class LazrsAppender(IPointAppender):
    """Appending in LAZ file
    works by seeking to start of the last chunk
    of compressed points, decompress it while keeping the points in
    memory.

    Then seek back to the start of the last chunk, and recompress
    the points we just read, so that we have a compressor in the proper state
    ready to compress new points.
    """
    def __init__(self, dest: BinaryIO, header: LasHeader, parallel: bool) -> None:
        ...
    
    def append_points(self, points: PackedPointRecord) -> None:
        ...
    
    def done(self) -> None:
        ...
    


