"""
This type stub file was generated by pyright.
"""

import abc
import ctypes
import numpy as np
from typing import Any, List, Optional, Tuple, TypeVar, Union
from ..point.format import ExtraBytesParams
from ..point.record import PackedPointRecord
from .vlr import BaseVLR, VLR

"""The definition of the VLR Header, VLR, the KnownVLRs
are in this module.

A KnownVLR is a VLR for which we know how to parse its record_data
"""
abstractmethod = ...
logger = ...
NULL_BYTE = ...
GeoKeyDirectoryType = TypeVar("GeoKeyDirectoryType", bound="GeoKeyDirectoryVlr")
GeoAsciiParamsType = TypeVar("GeoAsciiParamsType", bound="GeoAsciiParamsVlr")
class IKnownVLR(abc.ABC):
    """Interface that any KnownVLR must implement.
    A KnownVLR is a VLR for which we know how to parse its record_data

    Implementing this interfaces allows to automatically call the
    right parser for the right VLR when reading them.
    """
    @staticmethod
    @abstractmethod
    def official_user_id() -> str:
        """Shall return the official user_id as described in the documentation"""
        ...
    
    @staticmethod
    @abstractmethod
    def official_record_ids() -> Tuple[int, ...]:
        """Shall return the official record_id for the VLR

        .. note::

            Even if the VLR has one record_id, the return type must be a tuple

        Returns
        -------
        tuple of int
            The record_ids this VLR type can have
        """
        ...
    
    @abstractmethod
    def record_data_bytes(self) -> bytes:
        """Shall return the bytes corresponding to the record_data part of the VLR
        as they should be written in the file.

        Returns
        -------
        bytes
            The bytes of the vlr's record_data

        """
        ...
    
    @abstractmethod
    def parse_record_data(self, record_data: bytes) -> None:
        """Shall parse the given record_data into a user-friendlier structure

        Parameters
        ----------
        record_data: bytes
            The record_data bytes read from the file

        """
        ...
    


class BaseKnownVLR(BaseVLR, IKnownVLR, abc.ABC):
    """Base Class to factorize common code between the different type of Known VLRs"""
    def __init__(self, record_id=..., description=...) -> None:
        ...
    
    @classmethod
    def from_raw(cls, raw: VLR): # -> Self:
        ...
    


class ClassificationLookupVlr(BaseKnownVLR):
    """This vlr maps class numbers to short descriptions / names

    >>> lookup = ClassificationLookupVlr()
    >>> lookup[0] = "never_classified"
    >>> lookup[2] = "ground"
    >>> lookup[0]
    'never_classified'
    """
    _lookup_struct = ...
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, record_data: bytes) -> None:
        ...
    
    def record_data_bytes(self) -> bytes:
        ...
    
    def __getitem__(self, class_id: int) -> str:
        ...
    
    def __setitem__(self, class_id: int, description: str): # -> None:
        ...
    
    @staticmethod
    def official_user_id() -> str:
        ...
    
    @staticmethod
    def official_record_ids() -> Tuple[int, ...]:
        ...
    


class LasZipVlr(BaseKnownVLR):
    """Contains the information needed by laszip (or any other laz backend)
    to compress the point records.
    """
    def __init__(self, data: bytes) -> None:
        ...
    
    def parse_record_data(self, record_data: bytes) -> None:
        ...
    
    def record_data_bytes(self) -> bytes:
        ...
    
    @staticmethod
    def official_user_id() -> str:
        ...
    
    @staticmethod
    def official_record_ids() -> Tuple[int, ...]:
        ...
    
    @classmethod
    def from_raw(cls, raw_vlr): # -> Self:
        ...
    


class ExtraBytesStruct(ctypes.LittleEndianStructure):
    _pack_ = ...
    _fields_ = ...
    _uint64t_struct = ...
    _int64t_struct = ...
    _double_struct = ...
    NO_DATA_BIT_MASK = ...
    MIN_BIT_MASK = ...
    MAX_BIT_MASK = ...
    SCALE_BIT_MASK = ...
    OFFSET_BIT_MASK = ...
    def __init__(self, name: bytes, data_type: Union[int, Tuple[int, int]], description: bytes = ..., scale: Optional[np.ndarray] = ..., offset: Optional[np.ndarray] = ..., no_data: Optional[np.ndarray] = ...) -> None:
        ...
    
    @property
    def no_data(self): # -> ndarray[Any, Any] | None:
        ...
    
    @no_data.setter
    def no_data(self, value): # -> None:
        ...
    
    @property
    def min(self): # -> Any | ndarray[Any, Any] | None:
        ...
    
    @property
    def max(self): # -> Any | ndarray[Any, Any] | None:
        ...
    
    @property
    def offset(self) -> Optional[Any]:
        ...
    
    @offset.setter
    def offset(self, value): # -> None:
        ...
    
    @property
    def scale(self): # -> Any | None:
        ...
    
    @scale.setter
    def scale(self, value): # -> None:
        ...
    
    def format_name(self): # -> Any:
        ...
    
    def dtype(self) -> np.dtype:
        ...
    
    def num_elements(self) -> int:
        ...
    
    def min_is_relevant(self): # -> bool:
        ...
    
    def max_is_relevant(self): # -> bool:
        ...
    
    def grow(self, points: PackedPointRecord): # -> None:
        ...
    
    def partial_reset(self): # -> None:
        ...
    
    @staticmethod
    def size(): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class ExtraBytesVlr(BaseKnownVLR):
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    def type_of_extra_dims(self) -> List[ExtraBytesParams]:
        ...
    
    def grow(self, points: PackedPointRecord): # -> None:
        ...
    
    def partial_reset(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Spec']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[4]]:
        ...
    


class WaveformPacketStruct(ctypes.LittleEndianStructure):
    _pack_ = ...
    _fields_ = ...
    @staticmethod
    def size(): # -> int:
        ...
    


class WaveformPacketVlr(BaseKnownVLR):
    def __init__(self, record_id, description=...) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    @staticmethod
    def official_record_ids(): # -> range:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Spec']:
        ...
    
    @classmethod
    def from_raw(cls, raw_vlr): # -> Self:
        ...
    


class GeoKeyEntryStruct(ctypes.LittleEndianStructure):
    _pack_ = ...
    _fields_ = ...
    @staticmethod
    def size(): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class GeoKeysHeaderStructs(ctypes.LittleEndianStructure):
    _pack_ = ...
    _fields_ = ...
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def size(): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class GeoKeyDirectoryVlr(BaseKnownVLR):
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    def parse_crs(self): # -> CRS | None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Projection']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[34735]]:
        ...
    


class GeoDoubleParamsVlr(BaseKnownVLR):
    """
    Stores all of the `double` valued GeoKeys.
    """
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Projection']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[34736]]:
        ...
    


class GeoAsciiParamsVlr(BaseKnownVLR):
    """
    Stores all of the `ASCII` valued GeoKeys.

    From GeoTIFF's spec:
    To avoid problems with naive tiff dump programs the separator between geokeys is not
    the null-terminator `\0` but `|`.

    """
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Projection']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[34737]]:
        ...
    


class WktMathTransformVlr(BaseKnownVLR):
    """
    From the Spec:
        Note that the math transform WKT record is added for completeness, and a coordinate system WKT
        may or may not require a math transform WKT record

    """
    def __init__(self) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Projection']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[2111]]:
        ...
    


class WktCoordinateSystemVlr(BaseKnownVLR):
    """Replaces Coordinates Reference System for new las files (point fmt >= 5)
    "LAS is not using the “ESRI WKT”
    """
    def __init__(self, wkt_string=...) -> None:
        ...
    
    def parse_record_data(self, record_data): # -> None:
        ...
    
    def record_data_bytes(self): # -> bytes:
        ...
    
    def parse_crs(self): # -> CRS | None:
        ...
    
    @staticmethod
    def official_user_id(): # -> Literal['LASF_Projection']:
        ...
    
    @staticmethod
    def official_record_ids(): # -> tuple[Literal[2112]]:
        ...
    


def vlr_factory(vlr: VLR): # -> BaseKnownVLR | VLR:
    """Given a vlr tries to find its corresponding KnownVLR class
    that can parse its data.
    If no KnownVLR implementation is found, returns the input vlr unchanged
    """
    ...

