"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Union

class IVLR(ABC):
    @property
    @abstractmethod
    def user_id(self) -> str:
        ...
    
    @property
    @abstractmethod
    def record_id(self) -> int:
        ...
    
    @property
    @abstractmethod
    def description(self) -> Union[str, bytes]:
        ...
    
    @abstractmethod
    def record_data_bytes(self) -> bytes:
        ...
    


class BaseVLR(IVLR, ABC):
    def __init__(self, user_id, record_id, description=...) -> None:
        ...
    
    @property
    def user_id(self) -> str:
        """
        The user id
        """
        ...
    
    @property
    def record_id(self) -> int:
        """
        The record id
        """
        ...
    
    @property
    def description(self) -> Union[str, bytes]:
        """
        The description, cannot exceed 32 bytes
        """
        ...
    


class VLR(BaseVLR):
    """
    >>> import laspy
    >>> my_vlr = laspy.VLR(
    ... user_id="MyUserId",
    ... record_id=0,
    ... description="An Example VLR",
    ... record_data=int(42).to_bytes(8, byteorder='little'),
    ... )
    >>> my_vlr.user_id
    'MyUserId'
    >>> int.from_bytes(my_vlr.record_data, byteorder='little')
    42
    """
    def __init__(self, user_id, record_id, description=..., record_data=...) -> None:
        ...
    
    def record_data_bytes(self) -> bytes:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


