"""
This type stub file was generated by pyright.
"""

import numpy as np
from enum import Enum
from ..point import PointFormat

""" Contains the classes that manages Las PointRecords
Las PointRecords are represented using Numpy's structured arrays,
The PointRecord classes provide a few extra things to manage these arrays
in the context of Las point data
"""
logger = ...
def scale_dimension(array_dim, scale, offset):
    ...

def unscale_dimension(array_dim, scale, offset):
    ...

class DimensionNameValidity(Enum):
    """Helper class to make the return value of
    PackedPointRecord.validate_dimentsion_name more expressive.
    """
    Valid = ...
    Unsupported = ...
    Invalid = ...


class PackedPointRecord:
    """
    In the PackedPointRecord, fields that are a combinations of many sub-fields (fields stored on less than a byte)
    are still packed together and are only de-packed and re-packed when accessed.

    This uses of less memory than if the sub-fields were unpacked

    >>> #return number is a sub-field
    >>> from laspy import PointFormat, PackedPointRecord
    >>> packed_point_record = PackedPointRecord.zeros(10,PointFormat(0))
    >>> return_number = packed_point_record['return_number']
    >>> return_number
    <SubFieldView([0 0 0 0 0 0 0 0 0 0])>
    >>> return_number[:] = 1
    >>> bool(np.all(packed_point_record['return_number'] == 1))
    True
    """
    def __init__(self, data: np.ndarray, point_format: PointFormat) -> None:
        ...
    
    @property
    def point_size(self): # -> int:
        """Returns the point size in bytes taken by each points of the record

        Returns
        -------
        int
            The point size in byte

        """
        ...
    
    @staticmethod
    def zeros(point_count, point_format): # -> PackedPointRecord:
        """Creates a new point record with all dimensions initialized to zero

        Parameters
        ----------
        point_format: PointFormat
            The point format id the point record should have
        point_count : int
            The number of point the point record should have

        Returns
        -------
        PackedPointRecord

        """
        ...
    
    @staticmethod
    def empty(point_format): # -> PackedPointRecord:
        """Creates an empty point record.

        Parameters
        ----------
        point_format: laspy.PointFormat
            The point format id the point record should have

        Returns
        -------
        PackedPointRecord

        """
        ...
    
    @classmethod
    def from_point_record(cls, other_point_record: PackedPointRecord, new_point_format: PointFormat) -> PackedPointRecord:
        """Construct a new PackedPointRecord from an existing one with the ability to change
        to point format while doing so
        """
        ...
    
    @classmethod
    def from_buffer(cls, buffer, point_format, count=..., offset=...): # -> Self:
        ...
    
    def copy_fields_from(self, other_record: PackedPointRecord) -> None:
        """Tries to copy the values of the current dimensions from other_record"""
        ...
    
    def copy(self) -> PackedPointRecord:
        ...
    
    def memoryview(self) -> memoryview:
        ...
    
    def resize(self, new_size: int) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, item): # -> PackedPointRecord | SubFieldView | ScaledArrayView | NDArray[Any]:
        """Gives access to the underlying numpy array
        Unpack the dimension if item is the name a sub-field
        """
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets elements in the array"""
        ...
    
    def __getattr__(self, item): # -> PackedPointRecord | SubFieldView | ScaledArrayView | NDArray[Any]:
        ...
    
    def validate_dimension_name(self, key: str) -> DimensionNameValidity:
        """Given a name of a dimension this validates it."""
        ...
    
    def __setattr__(self, key, value): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


def apply_new_scaling(record, scales: np.ndarray, offsets: np.ndarray) -> None:
    ...

class ScaleAwarePointRecord(PackedPointRecord):
    """A ScaleAwarePointRecord is a point record that knows the scales and offets
    to use, and is thus able to get and set the scaled x, y, z coordinates

    To create one, use :meth:`.ScaleAwarePointRecord.zeros` or :meth:`.ScaleAwarePointRecord.empty`

    """
    def __init__(self, array, point_format, scales, offsets) -> None:
        ...
    
    @staticmethod
    def zeros(point_count, *, point_format=..., scales=..., offsets=..., header=...): # -> ScaleAwarePointRecord:
        """Creates a new point record with all dimensions initialized to zero

        Examples
        --------

        >>> record = ScaleAwarePointRecord.zeros(
        ... 5, point_format=PointFormat(3), scales=[1.0, 1.0, 1.0], offsets=[0.1, 0.5, 17.5])
        >>> len(record)
        5

        >>> import laspy
        >>> hdr = laspy.LasHeader()
        >>> record = ScaleAwarePointRecord.zeros(5, header=hdr)
        >>> len(record)
        5

        >>> hdr = laspy.LasHeader()
        >>> record = ScaleAwarePointRecord.zeros(5, header=hdr, scales=[1.0, 1.0, 1.0])
        Traceback (most recent call last):
        ValueError: header argument is mutually exclusive with point_format, scales and offets

        >>> record = ScaleAwarePointRecord.zeros(5, point_format=PointFormat(3))
        Traceback (most recent call last):
        ValueError: You have to provide all 3: point_format, scale and offsets
        """
        ...
    
    @staticmethod
    def empty(point_format=..., scales=..., offsets=..., header=...): # -> ScaleAwarePointRecord:
        """Creates an empty point record."""
        ...
    
    def change_scaling(self, scales=..., offsets=...) -> None:
        """See :meth:`.LasData.change_scaling`"""
        ...
    
    def __getitem__(self, item): # -> ScaleAwarePointRecord | ScaledArrayView | PackedPointRecord | SubFieldView | NDArray[Any]:
        ...
    
    def __setattr__(self, key, value): # -> None:
        ...
    


