"""
This type stub file was generated by pyright.
"""

"""Ground control points"""
class GroundControlPoint:
    """A mapping of row, col image coordinates to x, y, z."""
    def __init__(self, row=..., col=..., x=..., y=..., z=..., id=..., info=...) -> None:
        """Create a new ground control point

        Parameters
        ----------
        row, col : float, required
            The row (or line) and column (or pixel) coordinates that
            map to spatial coordinate values ``y`` and ``x``,
            respectively.
        x, y : float, required
            Spatial coordinates of a ground control point.
        z : float, optional
            Optional ``z`` coordinate.
        id : str, optional
            A unique identifier for the ground control point.
        info : str, optional
            A short description for the ground control point.
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def asdict(self): # -> dict[str, Any]:
        """A dict representation of the GCP"""
        ...
    
    @property
    def __geo_interface__(self): # -> dict[str, Any]:
        """A GeoJSON representation of the GCP"""
        ...
    


