"""
This type stub file was generated by pyright.
"""

from collections import UserDict

"""Raster dataset profiles."""
class Profile(UserDict):
    """Base class for Rasterio dataset profiles.

    Subclasses will declare driver-specific creation options.
    """
    defaults = ...
    def __init__(self, data=..., **kwds) -> None:
        """Create a new profile based on the class defaults, which are
        overlaid with items from the `data` dict and keyword arguments."""
        ...
    
    def __getitem__(self, key):
        """Like normal item access but with affine alias."""
        ...
    
    def __setitem__(self, key, val): # -> None:
        """Like normal item setter but forbidding affine item."""
        ...
    


class DefaultGTiffProfile(Profile):
    """Tiled, band-interleaved, LZW-compressed, 8-bit GTiff."""
    defaults = ...


default_gtiff_profile = ...
