"""
This type stub file was generated by pyright.
"""

import attr

@attr.s(slots=True)
class RPC:
    """Rational Polynomial Coefficients used to map (x, y, z) <-> (row, col) coordinates.
    
    This class contains a mapping between various RPC attributes and values. 

    Attributes
    ----------
    err_bias, err_rand: float, optional
        The RMS bias and random error in meters per horizontal axis of all points in image.
    lat_off, long_off, height_off: float
        Geodetic latitude, longitude, and height offset.
    lat_scale, long_scale, height_scale: float
        Geodetic latitude, longitude, and height scaling.
    line_off, samp_off: float
        Line (row) and sample (column) offset.
    line_scale, samp_scale: float
        Line (row) and sample (column) offset.
    line_num_coeff, line_den_coeff, samp_num_coeff, samp_den_coeff: list
        The twenty coefficients describing a numerator or denominator polynomial corresponding to line (row) or sample (col).
    """
    height_off = ...
    height_scale = ...
    lat_off = ...
    lat_scale = ...
    line_den_coeff = ...
    line_num_coeff = ...
    line_off = ...
    line_scale = ...
    long_off = ...
    long_scale = ...
    samp_den_coeff = ...
    samp_num_coeff = ...
    samp_off = ...
    samp_scale = ...
    err_bias = ...
    err_rand = ...
    def to_dict(self): # -> dict[str, Any]:
        """Return a dictionary representation of RPC"""
        ...
    
    def to_gdal(self): # -> dict[str, str]:
        """Serialize RPC attribute name and values in a form expected by GDAL.
        
        Returns
        -------
        dict

        Notes
        -----
        The `err_bias` and `err_rand` are optional, and are not written to datasets by GDAL.
        """
        ...
    
    @classmethod
    def from_gdal(cls, rpcs): # -> Self:
        """Deserialize dict values to float or list.


        Returns
        -------
        RPC
        """
        ...
    


