"""
This type stub file was generated by pyright.
"""

"""Rasterio tools module

See this RFC about Rasterio tools:
https://github.com/rasterio/rasterio/issues/1300.
"""
class JSONSequenceTool:
    """Extracts data from a dataset file and saves a JSON sequence
    """
    def __init__(self, func) -> None:
        """Initialize tool

        Parameters
        ----------
        func : callable
            A function or other callable object that takes a dataset and
            yields JSON serializable objects.
        """
        ...
    
    def __call__(self, src_path, dst_path, src_kwargs=..., dst_kwargs=..., func_args=..., func_kwargs=..., config=...): # -> None:
        """Execute the tool's primary function and perform file I/O

        Parameters
        ----------
        src_path : str or PathLike object
            A dataset path or URL. Will be opened in "r" mode using
            src_opts.
        dst_path : str or Path-like object
            A path or or PathLike object. Will be opened in "w" mode.
        src_kwargs : dict
            Options that will be passed to rasterio.open when opening
            src.
        dst_kwargs : dict
            Options that will be passed to json.dumps when serializing
            output.
        func_args : sequence
            Extra positional arguments for the tool's primary function.
        func_kwargs : dict
            Extra keyword arguments for the tool's primary function.
        config : dict
            Rasterio Env options.

        Returns
        -------
        None

        Side effects
        ------------
        Writes sequences of JSON texts to the named output file.
        """
        ...
    


dataset_features_tool = ...
